<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="SignUp" duration-ms="83070" started-at="2017-05-10T10:25:02Z" finished-at="2017-05-10T10:26:25Z">
    <groups>
    </groups>
    <test name="Sign Up" duration-ms="83070" started-at="2017-05-10T10:25:02Z" finished-at="2017-05-10T10:26:25Z">
      <class name="Test.JoinUsTest">
        <test-method status="PASS" signature="startingReport()[pri:0, instance:Test.JoinUsTest@68837a77]" name="startingReport" is-config="true" duration-ms="260" started-at="2017-05-10T11:25:02Z" finished-at="2017-05-10T11:25:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startingReport -->
        <test-method status="PASS" signature="browser()[pri:0, instance:Test.JoinUsTest@68837a77]" name="browser" is-config="true" duration-ms="18054" started-at="2017-05-10T11:25:03Z" finished-at="2017-05-10T11:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="FAIL" signature="signUp()[pri:0, instance:Test.JoinUsTest@68837a77]" name="signUp" duration-ms="56794" started-at="2017-05-10T11:25:21Z" finished-at="2017-05-10T11:26:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Show] but found [Home]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Show] but found [Home]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at PageFactory.ResponsiveMenu.assertPageTitle(ResponsiveMenu.java:75)
	at PageFactory.ResponsiveMenu.confirmRegistrationIsSuccessful(ResponsiveMenu.java:82)
	at Test.JoinUsTest.signUp(JoinUsTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Test.JoinUsTest@68837a77]" name="tearDown" is-config="true" duration-ms="7715" started-at="2017-05-10T11:26:17Z" finished-at="2017-05-10T11:26:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUp status=FAILURE method=JoinUsTest.signUp()[pri:0, instance:Test.JoinUsTest@68837a77] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endingReport()[pri:0, instance:Test.JoinUsTest@68837a77]" name="endingReport" is-config="true" duration-ms="231" started-at="2017-05-10T11:26:25Z" finished-at="2017-05-10T11:26:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endingReport -->
      </class> <!-- Test.JoinUsTest -->
    </test> <!-- Sign Up -->
  </suite> <!-- SignUp -->
</testng-results>
